blank_issues_enabled: false
contact_links:
  - name: SpringBlade 官方网站！
    url: https://bladex.cn
    about: BladeX企业级开发平台！！！
  - name: SpringBlade 社区！
    url: https://sns.bladex.cn
    about:  SpringBlade 技术社区！！！
